sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "Qux7aPxr2ba9kjZYRx/YUJxfTsEhPOq3LHrWTGq9jBywAXN40/c0Kd1lM+qftSX51uwo9RsWpFQ+fLfdbNKxQjyL3N/PBxbG+y7USwcXn0t6N78mWjh4oKU9CyIEtKn+zDIV2vDMtDsJzkxYXSSns41OPfkdOQK+LIQhb4lIfxUQej8V27rEPnpL8G8H4fFZ3IC4dVcjjUi+tcmM0RKw+6OPdXkRwwp28HGCF99GoisrBgD0xubwUjVnQLDPuTrU6CsKnuLI0SH8v76be/8C6IzF8R2tBrdi4BKR+RFLp0JKtcdTWEu+po0SqVUfT6MLr5M8F/TLF3EJ8JSZC3uIgACNCMP/2dJAUfJX7CaK5RGo+u0eKd3umU67mp9XjybswGKqRPsAnM0jaX3qJp1PhrbJH+HcJtDkamqCZ223QXBUep5Y5zrUuafzxFEWZOFD6nDLx7j4t8KeOhqd/RTW18jak4D9hzXsOvaVv9GFRbdxtD39zGYoSxOK1+VJrfD9rSgPD3AF5kHRv0Pld9sHSjPS1azLWHpRudB1mICGPCxcbA8dbnlxgOZ6BZtRhFWqC5SY2UwwThZNNT2aQxZfVQEjE5RCwt3IcZJqCx1k93jySyDHVrfOGwhLZHP5H9PZXkdyHMdSsUqK2QumAjMVou5ogJ5Dclmjrz+VNvB33h8="
branches:
  only:
    - main
